import streamlit as st
import pandas as pd
from datetime import datetime, timedelta
import google.generativeai as genai
import json
from fpdf import FPDF
import base64

# 1. UI SETUP
st.set_page_config(page_title="Smart Anesthesia", page_icon="💉", layout="wide")
st.markdown("""<style>.stButton>button {width: 100%; border-radius: 8px; background-color: #2E86C1; color: white;}</style>""", unsafe_allow_html=True)

# --- CLASS สำหรับสร้าง PDF (แก้ Error ภาษาไทย) ---
class PDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'SMART HOSPITAL - ANESTHESIA RECORD', 0, 1, 'C')
        self.set_font('Arial', '', 10)
        self.cell(0, 10, 'Generated by Smart Voice Logger AI', 0, 1, 'C')
        self.line(10, 30, 200, 30)
        self.ln(10)

    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

def clean_for_pdf(text):
    """ฟังก์ชันตัดตัวอักษรไทยทิ้ง เพื่อไม่ให้ PDF Error"""
    # แปลงเป็น string -> encode เป็น latin-1 (ถ้าตัวไหนไม่ใช่ ให้แทนที่ด้วย ?) -> decode กลับ
    return str(text).encode('latin-1', 'replace').decode('latin-1')

# 2. ฟังก์ชันดึงรายชื่อโมเดล
def get_available_models():
    if "GEMINI_API_KEY" not in st.secrets: return []
    try:
        genai.configure(api_key=st.secrets["GEMINI_API_KEY"])
        models = []
        for m in genai.list_models():
            if 'generateContent' in m.supported_generation_methods:
                models.append(m.name.replace("models/", ""))
        return models
    except: return []

# 3. SIDEBAR: เลือกโมเดล & DOWNLOAD
with st.sidebar:
    st.header("⚙️ Settings")
    backup_models = ["gemini-2.0-flash", "gemini-1.5-flash", "gemini-1.5-pro", "gemini-pro"]
    real_models = get_available_models()
    all_options = sorted(list(set(real_models + backup_models)))
    
    default_ix = 0
    if "gemini-2.0-flash" in all_options:
        default_ix = all_options.index("gemini-2.0-flash")
    elif "gemini-1.5-flash" in all_options:
        default_ix = all_options.index("gemini-1.5-flash")
    
    selected_model_name = st.selectbox("เลือก AI Model:", all_options, index=default_ix)
    
    st.divider()
    
    # --- ส่วนสร้าง PDF ---
    st.header("📄 Export Record")
    if 'logs' in st.session_state and not st.session_state.logs.empty:
        if st.button("📥 Generate PDF Report"):
            try:
                pdf = PDF()
                pdf.add_page()
                pdf.set_font("Arial", size=12)
                
                # Mock Patient Info
                pdf.cell(200, 10, txt="Patient Name: Mr. Somchai Jai-dee (Test Case)", ln=True)
                pdf.cell(200, 10, txt=f"Date: {datetime.now().strftime('%Y-%m-%d')}   HN: 67-001234", ln=True)
                pdf.cell(200, 10, txt="Procedure: Laparoscopic Appendectomy", ln=True)
                pdf.ln(10)
                
                # Table Header
                pdf.set_fill_color(200, 220, 255)
                pdf.set_font("Arial", 'B', 10)
                pdf.cell(30, 10, "Time", 1, 0, 'C', 1)
                pdf.cell(80, 10, "Item / Event", 1, 0, 'C', 1)
                pdf.cell(30, 10, "Qty", 1, 0, 'C', 1)
                pdf.cell(50, 10, "Category", 1, 1, 'C', 1)
                
                # Table Data
                pdf.set_font("Arial", size=10)
                for index, row in st.session_state.logs.iterrows():
                    # --- ใช้ clean_for_pdf ป้องกัน Error ---
                    t = clean_for_pdf(row['Time'])
                    i = clean_for_pdf(row['Item'])[:40] 
                    q = clean_for_pdf(f"{row['Qty']} {row['Unit']}")
                    c = clean_for_pdf(row['Category'])
                    
                    pdf.cell(30, 10, t, 1)
                    pdf.cell(80, 10, i, 1)
                    pdf.cell(30, 10, q, 1)
                    pdf.cell(50, 10, c, 1, 1)
                
                # Summary Section
                pdf.ln(10)
                pdf.set_font("Arial", 'B', 12)
                pdf.cell(200, 10, "Case Summary:", ln=True)
                pdf.set_font("Arial", size=10)
                
                try:
                    narc_sum = pd.to_numeric(st.session_state.logs[st.session_state.logs['Category'] == 'Narcotic']['Qty'], errors='coerce').fillna(0).sum()
                    crit_count = len(st.session_state.logs[st.session_state.logs['Category'] == 'Critical Event'])
                    pdf.cell(200, 8, f"- Total Narcotics Usage: {int(narc_sum)} (units)", ln=True)
                    pdf.cell(200, 8, f"- Critical Events Recorded: {crit_count}", ln=True)
                except:
                    pass

                pdf.ln(20)
                pdf.cell(200, 10, "__________________________", ln=True)
                pdf.cell(200, 10, "Anesthesiologist Signature", ln=True)

                pdf_bytes = pdf.output(dest='S').encode('latin-1', 'replace') 
                b64 = base64.b64encode(pdf_bytes).decode()
                href = f'<a href="data:application/octet-stream;base64,{b64}" download="Anesthesia_Record.pdf" style="text-decoration:none;"><button style="width:100%; background-color:#28B463; color:white; padding:10px; border:none; border-radius:5px; cursor:pointer;">✅ Click to Download PDF</button></a>'
                st.markdown(href, unsafe_allow_html=True)
                
            except Exception as e:
                st.error(f"PDF Error: {e}")
    else:
        st.info("No data to export yet.")

# 4. AI FUNCTION
def process_command(cmd):
    if "GEMINI_API_KEY" not in st.secrets: return {"error": "API Key Missing"}
    try:
        genai.configure(api_key=st.secrets["GEMINI_API_KEY"])
        model = genai.GenerativeModel(selected_model_name)
        
        prompt = f"""
        Act as an Expert Anesthesia Assistant.
        Analyze input: "{cmd}"
        Task: Extract ALL medical items/events.
        Rules:
        1. Return JSON ARRAY of objects.
        2. Keys: "item", "qty", "unit", "category".
        3. If using Thai input, translate item name to English.
        4. Category list: [Narcotic, Vasoactive, Induction, Muscle Relaxant, Antibiotic, Equipment, Critical Event, General].
        Example: [ {{"item": "Fentanyl", "qty": 100, "unit": "mcg", "category": "Narcotic"}} ]
        """
        response = model.generate_content(prompt)
        text = response.text.replace("```json", "").replace("```", "").strip()
        return json.loads(text)
    except Exception as e:
        return {"error": str(e)}

# 5. MAIN UI
c1, c2 = st.columns([1, 5])
with c1: st.image("https://img.icons8.com/color/96/anesthetist.png", width=60)
with c2: st.title("Smart Anesthesia Logger")

cmd = st.text_input("ป้อนคำสั่ง (Voice/Text):", key="cmd")

if st.button("🚀 ส่งคำสั่ง (Submit)"):
    if cmd:
        with st.spinner(f"AI ({selected_model_name}) Processing..."):
            res = process_command(cmd)
            
            if isinstance(res, dict) and "error" in res:
                st.error(f"❌ Error: {res['error']}")
            else:
                items_to_save = res if isinstance(res, list) else [res]
                
                for entry in items_to_save:
                    item = entry.get('item') or entry.get('Item') or "Unknown"
                    qty = entry.get('qty') or entry.get('Qty') or 1
