import streamlit as st
import pandas as pd
from datetime import datetime, timedelta
import google.generativeai as genai
import json
from fpdf import FPDF
import base64

# 1. UI SETUP & INITIALIZATION
st.set_page_config(page_title="Smart Anesthesia", page_icon="💉", layout="wide")
st.markdown("""<style>.stButton>button {width: 100%; border-radius: 8px; background-color: #2E86C1; color: white;}</style>""", unsafe_allow_html=True)

if 'logs' not in st.session_state: 
    st.session_state.logs = pd.DataFrame(columns=['Time','Item','Qty','Unit','Category'])

# --- PDF CLASS ---
class PDF(FPDF):
    def header(self):
        self.set_font('Arial', 'B', 15)
        self.cell(0, 10, 'SMART HOSPITAL - ANESTHESIA RECORD', 0, 1, 'C')
        self.set_font('Arial', '', 10)
        self.cell(0, 10, 'Generated by Smart Voice Logger AI', 0, 1, 'C')
        self.line(10, 30, 200, 30)
        self.ln(10)
    def footer(self):
        self.set_y(-15)
        self.set_font('Arial', 'I', 8)
        self.cell(0, 10, f'Page {self.page_no()}', 0, 0, 'C')

def clean_for_pdf(text):
    return str(text).encode('latin-1', 'replace').decode('latin-1')

# 2. MODEL FETCHING
def get_available_models():
    if "GEMINI_API_KEY" not in st.secrets: return []
    try:
        genai.configure(api_key=st.secrets["GEMINI_API_KEY"])
        models = []
        for m in genai.list_models():
            if 'generateContent' in m.supported_generation_methods:
                models.append(m.name.replace("models/", ""))
        return models
    except: return []

# 3. SIDEBAR
with st.sidebar:
    st.header("⚙️ Settings")
    backup_models = ["gemini-2.0-flash", "gemini-1.5-flash", "gemini-1.5-pro", "gemini-pro"]
    real_models = get_available_models()
    all_options = sorted(list(set(real_models + backup_models)))
    
    # พยายามใช้ 1.5-flash เป็นค่า Default แทน 2.0 เพราะ 2.0 อาจจะ Safety จัดเกินไปในบางยา
    default_ix = 0
    if "gemini-1.5-flash" in all_options:
        default_ix = all_options.index("gemini-1.5-flash")
    elif "gemini-2.0-flash" in all_options:
        default_ix = all_options.index("gemini-2.0-flash")
    
    selected_model_name = st.selectbox("เลือก AI Model:", all_options, index=default_ix)
    st.info(f"Using: {selected_model_name}")
    st.divider()
    
    # PDF Export
    st.header("📄 Export Record")
    if not st.session_state.logs.empty:
        if st.button("📥 Generate PDF Report"):
            try:
                pdf = PDF()
                pdf.add_page()
                pdf.set_font("Arial", size=12)
                pdf.cell(200, 10, txt="Patient Name: Mr. Somchai (Test Case)", ln=True)
                pdf.cell(200, 10, txt=f"Date: {datetime.now().strftime('%Y-%m-%d')}", ln=True)
                pdf.ln(10)
                pdf.set_fill_color(200, 220, 255)
                pdf.set_font("Arial", 'B', 10)
                for h, w in zip(["Time", "Item / Event", "Qty", "Category"], [30, 80, 30, 50]):
                    pdf.cell(w, 10, h, 1, 0, 'C', 1)
                pdf.ln()
                pdf.set_font("Arial", size=10)
                for _, row in st.session_state.logs.iterrows():
                    pdf.cell(30, 10, clean_for_pdf(row['Time']), 1)
                    pdf.cell(80, 10, clean_for_pdf(row['Item'])[:40], 1)
                    pdf.cell(30, 10, clean_for_pdf(f"{row['Qty']} {row['Unit']}"), 1)
                    pdf.cell(50, 10, clean_for_pdf(row['Category']), 1, 1)
                pdf_bytes = pdf.output(dest='S').encode('latin-1', 'replace')
                b64 = base64.b64encode(pdf_bytes).decode()
                href = f'<a href="data:application/octet-stream;base64,{b64}" download="Anesthesia_Record.pdf" style="text-decoration:none;"><button style="width:100%; background-color:#28B463; color:white; padding:10px; border:none; border-radius:5px;">✅ Click to Download PDF</button></a>'
                st.markdown(href, unsafe_allow_html=True)
            except Exception as e:
                st.error(f"PDF Error: {e}")

# 4. AI FUNCTION (Robust Version)
def process_command(cmd):
    if "GEMINI_API_KEY" not in st.secrets: return {"error": "API Key Missing"}
    try:
        genai.configure(api_key=st.secrets["GEMINI_API_KEY"])
        
        # ปิด Safety Filter (เพื่อให้ยอมตอบเรื่องยาได้มากขึ้น)
        safety_settings = [
            {"category": "HARM_CATEGORY_HARASSMENT", "threshold": "BLOCK_NONE"},
            {"category": "HARM_CATEGORY_HATE_SPEECH", "threshold": "BLOCK_NONE"},
            {"category": "HARM_CATEGORY_SEXUALLY_EXPLICIT", "threshold": "BLOCK_NONE"},
            {"category": "HARM_CATEGORY_DANGEROUS_CONTENT", "threshold": "BLOCK_NONE"},
        ]
        
        model = genai.GenerativeModel(selected_model_name, safety_settings=safety_settings)
        
        prompt = f"""
        Act as a Medical Logger. Analyze: "{cmd}"
        Rules:
        1. Return strictly a JSON ARRAY.
        2. Keys: "item", "qty", "unit", "category".
        3. Translate Thai to English.
        4. Category: [General, Narcotic, Antibiotic, Equipment, Critical Event, Induction, Vasoactive].
        Example: [ {{"item": "Ephedrine", "qty": 6, "unit": "mg", "category": "Vasoactive"}} ]
        """
        
        response = model.generate_content(prompt)
        
        # --- ดักจับ Case ที่ AI ไม่ยอมตอบ (Error Handling) ---
        if not response.text:
            return {"error": "AI ตอบกลับมาเป็นค่าว่าง (อาจติด Safety Filter)"}
            
        clean_text = response.text.replace("```json", "").replace("```", "").strip()
        
        try:
            return json.loads(clean_text)
        except json.JSONDecodeError:
            # ถ้าแกะ JSON ไม่ได้ ให้ส่ง Error กลับไปบอก User แทนที่จะ App ล่ม
            return {"error": f"AI ตอบกลับผิดรูปแบบ: {clean_text[:50]}..."}
            
    except Exception as e:
        return {"error": str(e)}

# 5. MAIN UI
c1, c2 = st.columns([1, 5])
with c1: st.image("https://img.icons8.com/color/96/anesthetist.png", width=60)
with c2: st.title("Smart Anesthesia Logger")

cmd = st.text_input("ป้อนคำสั่ง (Voice/Text):", key="cmd")

if st.button("🚀 ส่งคำสั่ง (Submit)"):
    if cmd:
        with st.spinner(f"AI ({selected_model_name}) Processing..."):
            res = process_command(cmd)
            
            # เช็ค Error แบบละเอียด
            if isinstance(res, dict) and "error" in res:
                st.error(f"❌ {res['error']}")
                st.warning("คำแนะนำ: ลองเปลี่ยนรุ่น AI เป็น 'gemini-1.5-flash' หรือพิมพ์ให้ชัดเจนขึ้นครับ")
            
            else:
                items_to_save = res if isinstance(res, list) else [res]
                
                if not items_to_save:
                    st.warning("⚠️ AI ไม่เข้าใจคำสั่งนี้ครับ")
                
                count = 0
                for entry in items_to_save:
                    item = entry.get('item') or entry.get('Item') or "Unknown"
                    qty = entry.get('qty') or entry.get('Qty') or 1
                    unit = entry.get('unit') or entry.get('Unit') or "-"
                    cat = entry.get('category') or entry.get('Category') or "General"
                    
                    thai_time = (datetime.now() + timedelta(hours=7)).strftime("%H:%M:%S")
                    new_row = {'Time': thai_time, 'Item': item, 'Qty': qty, 'Unit': unit, 'Category': cat}
                    st.session_state.logs = pd.concat([pd.DataFrame([new_row]), st.session_state.logs], ignore_index=True)
                    count += 1
                
                if count > 0:
                    st.success(f"✅ Saved {count} items!")

if 'logs' in st.session_state and not st.session_state.logs.empty:
    st.divider()
    st.subheader("📊 Dashboard")
    try:
        narc_sum = pd.to_numeric(st.session_state.logs[st.session_state.logs['Category'] == 'Narcotic']['Qty'], errors='coerce').fillna(0).sum()
        crit_count = len(st.session_state.logs[st.session_state.logs['Category'] == 'Critical Event'])
        m1, m2, m3 = st.columns(3)
        m1.metric("Narcotics", f"{int(narc_sum)}")
        m2.metric("Critical Events", f"{crit_count}", delta_color="inverse")
        m3.metric("Total Logs", len(st.session_state.logs))
    except: pass
    st.dataframe(st.session_state.logs, use_container_width=True, hide_index=True)
else:
    st.info("💡 ระบบพร้อมแล้ว! ลองพิมพ์ 'Start Case' หรือ 'Fentanyl 50' ได้เลยครับ")
